In [3]:
import pandas as pd

In [12]:
df = pd.read_csv("ecommerce_sales_customer_behavior.csv")
df

,order_id,year,month,quarter,is_weekend_order,platform,country,customer_segment,customer_age_group,customer_gender,...,return_reason,customer_satisfaction,session_duration_minutes,pages_viewed,cart_abandoned_before,wishlist_used,coupon_used,subscription_member,repeat_purchase_count,loyalty_points
0,ORD0000001,2022,4,Q2,Yes,AliExpress,Germany,New Customer,35-44,Male,...,NaN,Dissatisfied,78.7,2,Yes,No,No,No,0,0
1,ORD0000002,2023,6,Q2,Yes,Flipkart,Australia,Loyal Customer,35-44,Male,...,NaN,Neutral,18.2,7,No,Yes,No,No,9,198
2,ORD0000003,2022,2,Q1,Yes,Amazon,Turkey,VIP Customer,45-54,Male,...,NaN,Very Dissatisfied,5.1,1,No,No,No,Yes,30,1020
3,ORD0000004,2022,7,Q3,No,AliExpress,USA,New Customer,35-44,Male,...,NaN,Satisfied,22.0,6,Yes,No,No,Yes,0,0
4,ORD0000005,2024,4,Q2,No,Daraz,Australia,Loyal Customer,35-44,Female,...,NaN,Satisfied,4.5,8,Yes,No,Yes,No,13,598
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,ORD0009996,2022,3,Q1,No,Amazon,Australia,VIP Customer,45-54,Male,...,NaN,Very Satisfied,14.1,6,No,No,No,Yes,47,2021
9996,ORD0009997,2021,11,Q4,No,Amazon,India,VIP Customer,45-54,Female,...,NaN,Satisfied,44.5,8,No,No,No,No,37,814
9997,ORD0009998,2021,10,Q4,Yes,eBay,Pakistan,Loyal Customer,65+,Male,...,NaN,Satisfied,8.9,8,Yes,No,No,No,5,50
9998,ORD0009999,2023,2,Q1,Yes,eBay,Bangladesh,New Customer,35-44,Female,...,NaN,Satisfied,62.4,4,No,Yes,Yes,No,0,0
9999,ORD0010000,2023,6,Q2,No,Shopify Store,India,VIP Customer,18-24,Male,...,NaN,Satisfied,14.0,2,No,No,No,No,32,928

En el df aparecen variables que representan fechas,informacion que identifica al cliente, como el pais, genero, edad, el tipo de cliente que es,datos sobre el tipo de compra que realizo, cuan recurrente es  y datos ordinales representados en si y no (1 y 0).

In [13]:
df[df["final_amount_usd"] > 500]

,order_id,year,month,quarter,is_weekend_order,platform,country,customer_segment,customer_age_group,customer_gender,...,return_reason,customer_satisfaction,session_duration_minutes,pages_viewed,cart_abandoned_before,wishlist_used,coupon_used,subscription_member,repeat_purchase_count,loyalty_points
2,ORD0000003,2022,2,Q1,Yes,Amazon,Turkey,VIP Customer,45-54,Male,...,NaN,Very Dissatisfied,5.1,1,No,No,No,Yes,30,1020
7,ORD0000008,2024,10,Q4,Yes,eBay,India,New Customer,55-64,Male,...,NaN,Satisfied,12.8,6,Yes,No,No,No,0,0
13,ORD0000014,2022,3,Q1,Yes,AliExpress,UAE,VIP Customer,35-44,Female,...,NaN,Satisfied,22.4,4,No,No,Yes,No,46,1242
18,ORD0000019,2022,3,Q1,No,eBay,UAE,Returning Customer,25-34,Female,...,Size Issue,Satisfied,109.3,6,No,Yes,No,Yes,4,60
22,ORD0000023,2023,3,Q1,Yes,Amazon,UK,Loyal Customer,35-44,Male,...,NaN,Satisfied,78.5,6,Yes,Yes,No,No,6,264
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9986,ORD0009987,2024,7,Q3,Yes,eBay,Germany,Loyal Customer,35-44,Male,...,NaN,Very Satisfied,8.8,6,Yes,No,No,Yes,13,403
9990,ORD0009991,2024,2,Q1,Yes,eBay,India,Loyal Customer,45-54,Male,...,NaN,Neutral,48.1,6,Yes,No,No,Yes,9,216
9992,ORD0009993,2021,8,Q3,Yes,Flipkart,UAE,VIP Customer,55-64,Female,...,NaN,Very Satisfied,76.8,7,Yes,No,Yes,Yes,36,1512
9993,ORD0009994,2024,1,Q1,No,Daraz,India,Inactive Customer,35-44,Male,...,NaN,Satisfied,22.1,6,No,Yes,No,No,0,0
9995,ORD0009996,2022,3,Q1,No,Amazon,Australia,VIP Customer,45-54,Male,...,NaN,Very Satisfied,14.1,6,No,No,No,Yes,47,2021

1. 3209 pedidos tienen un monto final superior a 500USD

In [14]:
np = df["customer_segment"].value_counts(1)
np

customer_segment
Returning Customer    0.2977
New Customer          0.2522
Loyal Customer        0.2166
VIP Customer          0.1213
Inactive Customer     0.1122
Name: proportion, dtype: float64

2. El 12% de los pedidos realizados son por VIP Customer

In [15]:
df.type()

AttributeError: 'DataFrame' object has no attribute 'type'

In [ ]:
df.query("customer_age_group == '25-34' and customer_gender == 'Female'")
df.query("customer_segment == 25-34 and customer_gender == Female")

UndefinedVariableError: name 'Female' is not defined

In [16]:
gf["customer_gender"].value_counts(1)

NameError: name 'gf' is not defined